### ISSUE TITLE
[Suggestion] Keybinds as dynamic tip content

### ISSUE THREAD

**Issue by LolJohn11** [Darkhax-Minecraft/Tips#100]
Say, for example, that I have a mod in my modpack that has a flashlight item with a keybind that toggles it on and off.
I make a tip that says "Press 'L' to turn your flashlight on or off."
But what if the user changes the keybind? Then the tip will show incorrect content that is no longer relevant.
What if we could specify the keybind as something that the mod will check for before displaying the tip so it always stays true to what the user set it to?
And have it work something like this:
```
modpack.tip.flashlight = "Press 'flashlightkey' to turn your flashlight on or off."

modpack.keybind.flashlightkey = "key.flashlightmod.flashlightToggle"
```

**Comment by Darkhax** [comment]
This mod uses Mojang's [raw JSON text format](https://minecraft.fandom.com/wiki/Raw_JSON_text_format) which supports this feature already. Use an array of components and use the [keybind component type](https://minecraft.fandom.com/wiki/Raw_JSON_text_format#Keybind) where you want to insert the keybind button. If you need help there are tools like [this](https://www.minecraftjson.com/) to help generate raw JSON text. 

Here is an example.
```json
{
  "tip": [
    "Press the \"",
    {
      "keybind": "key.drop"
    },
    "\" key to drop items."
  ]
}
```

and this is what it looks like in game.

![image](https://user-images.githubusercontent.com/2250798/198865939-8b6fafda-5f6e-4e16-a391-7facd0a85c5c.png)

Support for the raw JSON text format was added in 1.16.5. I am no longer updating versions older than 1.18.2.
