### ISSUE TITLE
There is a grammar issue in the tip about goats pushing players

### ISSUE THREAD

**Issue by Jmooroof** [Darkhax-Minecraft/Tips#113]
"tipsmod.tip.mean_goats": "Be careful around goats, they like to push players and other animals off cliffs.",
"Be careful arround goats" and "they like to push players and other animals off cliffs" are independent clauses, so that means u cant' combine them with a comma.
You should use "Be careful around goats because they like to push players and other animals off cliffs." or "Be careful around goats; they like to push players and other animals off cliffs."

**Comment by Darkhax** [comment]
Thanks, this has been changed.
