### ISSUE TITLE
[Suggestion] Replace default tips

### ISSUE THREAD

**Issue by OMG67** [Darkhax-Minecraft/Tips#114]
I've been looking around and couldn't find neither in the wiki nor the curseforge page for a way to replace the default tips, if it exists I apologise, but if it doesn't I think it would be a nice addition.

**Comment by Darkhax** [comment]
Hello, generally people disable the built in tips and then add new ones using the information in the wiki. All built in tips have the namespace of `tipsmod` so you can just disable that namespace in the config to disable all current and future builtin tips.

If you actually want to replace the existing tips and not just add your own tips, you can use a resource pack to override the existing text.
