### ISSUE TITLE
Ability to disable namespaces with intermod comms (Forge) or some other feature

### ISSUE THREAD

**Issue by eerussianguy** [Darkhax-Minecraft/Tips#116]
So I know namespaces are disabled via config, but it would be useful if a mod that wants to explicitly add tips themselves had the ability to filter namespaces without a soft dependency on Tips and having to manipulate the config. Basically, I want to handle this for my users rather than having by default my tips mixed in with vanilla tips. Stuff like Curios works like this, you just listen to the inter mod comms event and send a text message across if you detect the right mod id, and the mod handles it.

**Comment by Darkhax** [comment]
Thanks for the request. I understand what you're asking for but I don't know if this is something I want to encourage 3rd party mods to do VIA the API. The intent behind the current system is for modpacks and end users to have complete control over the configuration so they have the exact results they want. My worry is that implementing this feature will lead to issue reports from pack devs and users wondering why their tips do not work as expected. We also need to consider that 3rd party mods use a variety of namespaces and end users will semi-regularly put their tips in the default namespace so you would inadvertently override their changes.

**Comment by Darkhax** [comment]
Feel free to re-open this issue or reach out on Discord if you'd like to discuss the merits of this later on. Closing this as a stale issue for now.
