### ISSUE TITLE
Allow custom localized tips

### ISSUE THREAD

**Issue by misterplus** [Darkhax-Minecraft/Tips#12]
I already saw the commit https://github.com/Darkhax-Minecraft/Tips/commit/32767e2754802eb923d6f612602781cf566af935,
but the latest build on curseforge does not include it, can we get a new version that includes that?

oops, missed alpha release, I'll close now.

**Comment by Darkhax** [comment]
I've marked that build as a proper release on CurseForge so it should be easier to find now.
