### ISSUE TITLE
Crash [1.18.2]

### ISSUE THREAD

**Issue by MaxWasUnavailable** [Darkhax-Minecraft/Tips#124]
Versions:
- Minecraft: 1.18.2
- Forge: 40.2.1
- Tips: Tips-Forge-1.18.2-5.0.11.jar

Crash report:
https://cdn.discordapp.com/attachments/888135080172744814/1097261408330203186/crash-2023-04-16_22.33.44-client.txt

**Comment by Darkhax** [comment]
Hey, it looks like one of the mixin coremods you have installed has a bug or incompatibility. These are the mods it says you have installed that are modifying this code. Try removing them or other mods you have installed until you can track down who's breaking it.

- oculus
- oculus-batched-entity-rendering
- flywheel
- immediatelyfast
- rubidium
- irisflw

**Comment by MaxWasUnavailable** [comment]
Seems to potentially be related to Immersive Engineering. Removing an IE item from their inventory stopped the crash.

**Comment by Darkhax** [comment]
The log does not show immersive engineering being involved with the crash, so that's likely just a coincidence. But I guess the issue is resolved either way.
