### ISSUE TITLE
Please update your mod to Minecraft version 1.20.

### ISSUE THREAD

**Issue by surfishs** [Darkhax-Minecraft/Tips#125]
Please update your mod to Minecraft version 1.20.

**Comment by RisPNG** [comment]
> Please update your mod to Minecraft version 1.20.

as a workaround, open the .jar file as an archive and modify the "fabric.mod.json" file. look for the "minecraft" field and change the version to 1.20.x

edit: this is for those who're getting an error on 1.20.1

**Comment by Darkhax** [comment]
Alternatively you could use the [official 1.20 builds](https://www.curseforge.com/minecraft/mc-mods/tips/files?version=1.20). It should work on 1.20.1 as well but proper builds will be out for that in a few days.
