### ISSUE TITLE
replace/fix existing tips

### ISSUE THREAD

**Issue by Aceplante** [Darkhax-Minecraft/Tips#126]
there are a few that I would like to edit, how would I go about that. Is the ONLY option to add more?

**Comment by Darkhax** [comment]
All tips are created and managed using resource packs. You can change the properties of the tip by creating a tip json file with the same path and name as the one you want to replace. If you only want to replace the text that shows up you can create an entry in your resource packs en_us.json lang file. Removing tips entirely can be done using the config file which allows specific tips to be disabled by ID or all tips with a specific namespace to be disabled.
