### ISSUE TITLE
[Suggestion] Config

### ISSUE THREAD

**Issue by CarpenterV** [Darkhax-Minecraft/Tips#128]
I think the config should be expanded like Minecraft's splash text config where you can remove, customize, and add you own tips with ease. Would greatly increase ease of use and customizability for mod pack creators.

**Comment by Darkhax** [comment]
Hello, the current JSON based system already supports all of the features you have asked for while also supporting features that a simple config could not, such as custom titles, alternative fonts, language localization, and complex style formats. The JSON format used here is the same format used by Mojang for commands, signs, and other text customization so it seems like a reasonable skill requirement to use this mod. 

Here are some resources to help you out.
- [Documentation on the tips system](https://github.com/Darkhax-Minecraft/Tips/wiki/1.16.3-Documentation)
- [Minecraft text editor](https://www.minecraftjson.com/)
- [Example pack with custom tips](https://darkhax.net/assets/tips/Example-Tip-Pack-1.0.0.zip)
- [Builtin tips files](https://github.com/Darkhax-Minecraft/Tips/tree/1.20/common/src/main/resources/assets/tipsmod/tips)
