### ISSUE TITLE
[1.19.2 Forge] Crash before main menu

### ISSUE THREAD

**Issue by chorbintime** [Darkhax-Minecraft/Tips#130]
Very rare crash, consistently reproducable only on this one user's machine
They said their computer is very old, which may be a factor here. Nobody else has reported this issue.

Modpack is BMC3 Forge, latest version. We are using the latest version of the Tips mod. Most other mods are also up to date, including the modloader itself. Logs attached

[message (1).txt](https://github.com/Darkhax-Minecraft/Tips/files/12365654/message.1.txt)
[message.txt](https://github.com/Darkhax-Minecraft/Tips/files/12365655/message.txt)

**Comment by Darkhax** [comment]
The system isn't that old, they're using Ryzen 3. Looks like an issue reading their config file, I am guessing it's corrupted or malformed? Ask them to delete the config file and then try loading.

**Comment by chorbintime** [comment]
There a few things I would like to note -

1. We use the Night Config Fixes mod, which fixes/remedies a majority of instances of config corruption
2. We don't ship a Tips config with the modpack, so any corruption would've taken place before the game reached the main menu for the first time

Nonetheless, I will ask them to delete the config & retry

**Comment by chorbintime** [comment]
![DiscordPTB_STO424q8rD](https://github.com/Darkhax-Minecraft/Tips/assets/112908845/d4f15658-5f76-48ff-a382-b2ccecc9ee55)

**Comment by Darkhax** [comment]
I don't use Night Config because it's been way too unreliable. Looks like their config got corrupted on generation, potentially because the game crashed on an earlier load while the file was being written. I will add some checks to detect and warn about this in newer versions.
