### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by knoxhack** [Darkhax-Minecraft/Tips#131]
crash: [https://gist.githubusercontent.com/knoxhack/22c70dbf02646905e06f15ded7137930/raw/0d30b9036d0fa32587a7020093019073e27fca32/tips](https://gist.githubusercontent.com/knoxhack/22c70dbf02646905e06f15ded7137930/raw/0d30b9036d0fa32587a7020093019073e27fca32/tips)

**Comment by Darkhax** [comment]
Hey, I don't think this has anything to do with Rubidium. It looks like you or something you're using added a tip with no text so it's crashing when it tries to render. I've pushed an update that adds some extra safety nets for this. The game should no longer crash but you will have errors in your logs that you should resolve.

**Comment by knoxhack** [comment]
Thank you! I'll look into that.
I just updated all mods in my modpack and started getting this crash after. No new mods added.
