### ISSUE TITLE
Tips showing up for mods that are not loaded

### ISSUE THREAD

**Issue by eldabys** [Darkhax-Minecraft/Tips#138]
On version 12.0.3 for Forge. Installed and then removed the mod Galosphere, but its tips continue to show up.

**Comment by Darkhax** [comment]
The Galosphere mod does not have any built in tips and this mod does not add any tips on its behalf. Any tips related to the Galosphere mod are being added by a 3rd party mod pack or resource pack that you have not uninstalled.
