### ISSUE TITLE
[BUG] Tips do not show with "Drippy loading screen" installed

### ISSUE THREAD

**Issue by ZeroAresIV** [Darkhax-Minecraft/Tips#145]
### Minecraft Version

1.20.1

### Mod Version

1.20.1-Forge-12.1.7

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

When Loading into a world with the mod installed, tips are not rendered or renderable on the loading screen,

**Comment by Darkhax** [comment]
Could you please try with the new [21.1.8 update](https://www.curseforge.com/minecraft/mc-mods/tips/files/5547510) and try again?
