### ISSUE TITLE
[1.12.2] Tips continue to appear after mod uninstalled

### ISSUE THREAD

**Issue by BadRAM** [Darkhax-Minecraft/Tips#149]
### Minecraft Version

1.12.2

### Mod Version

1.0.9

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

I have fully deleted the mod jar file from my mods folder, the game launch log doesn't mention tips at all, and somehow the tips are still present on the level loading screen.

**Comment by Darkhax** [comment]
Deleting the mod jar will fully delete the mod. It does not install or extract anything to your game files. It's possible that another mod is displaying tips or you are looking at and/or launching the wrong game profile.

**Comment by BadRAM** [comment]
Thanks, I'll keep looking then. Do you recognize this pro tip dialog? 
![image](https://github.com/user-attachments/assets/4063f1cf-ddc5-449e-9071-0ac030ed0af8)

**Comment by Darkhax** [comment]
That looks like it might be the Aether mod. The tips added by this mod are on the bottom left and have separate title and body components. 
![tip_screenshot_1](https://github.com/user-attachments/assets/9bf4ccb9-5840-493c-9c76-260053c74fc1)

**Comment by BadRAM** [comment]
alright that makes sense. I did notice the difference from the curseforge screenshots, but many mods look completely different in 1.12.2 from their updated form, so I assumed it was still coming from Tips.

Edit: These tips were from Aether, good catch.
