### ISSUE TITLE
[1.16.3] CME client crash - 

### ISSUE THREAD

**Issue by ProsperCraft** [Darkhax-Minecraft/Tips#22]
Stacktrace in log-
https://gist.github.com/ProsperCraft/a241e17d02fd7195e8a89d6bc5fc1be1
Crash log-
https://gist.github.com/ProsperCraft/928c2109b0ab9a85f04c03ffc4bbdd5a
Full log-
https://gist.github.com/ProsperCraft/223d7d3ca723e8b450218c111a20ea52

Modpack-
[TownCraft TWO for 1.16](https://www.curseforge.com/minecraft/modpacks/towncraft)

Tips was working great in the pack, it started with this update, and happens every load.

Changelog-
https://gist.github.com/ProsperCraft/42951021c44d0e17eeff04b00a6dfe8f

**Comment by ProsperCraft** [comment]
Does this forge change have anything to do with it?

`Build: 1.16.3-34.1.35 - Thu Oct 29 17:09:31 GMT 2020
	malte0811:
		Fix (NonNull)Lazy.Concurrent using a global lock (#7403)
		
		* Fix Lazy.Concurrent using a global lock, thus preventing multiple threads from resolving independent Lazy's at the same time
		* Use Lazy with an added null check to implement NonNullLazy`

**Comment by ProsperCraft** [comment]
I removed Tips and Silent Gear did the same thing.

**Comment by Darkhax** [comment]
I am looking into this issue, it's very weird to see this. Also this is completely unrelated to the issues you've linked.

**Comment by Darkhax** [comment]
Have you been able to reproduce this issue without any other issues happening at the same time? This appears to be either a vanilla bug or another mod that is reloading resources before the initial load has completed.

**Comment by Darkhax** [comment]
This issue has remained illusive in normal environments and on newer versions of Forge. It's likely that the bug in Forge, or wherever the origin of the bug has been fixed. Feel free to re-open if this issue pops up again in the future.
