### ISSUE TITLE
Some way to manually view tips

### ISSUE THREAD

**Issue by EXPerience255** [Darkhax-Minecraft/Tips#28]
I would like a possible way to have the option of manually viewing tips without the randomness. Possibly could be a part of the .config file.

The reason I want this is because I want to make sure that custom tips that I make work, as I'm only seeing base tips. This might also be useful for others, too, and possibly for the same reason.

**Comment by Darkhax** [comment]
Hello, thanks for the suggestion. I will look into providing a GUI or something that will let you do this.

**Comment by EXPerience255** [comment]
> Hello, thanks for the suggestion. I will look into providing a GUI or something that will let you do this.

Thanks!

**Comment by Darkhax** [comment]
This feature has been added in https://github.com/Darkhax-Minecraft/Tips/commit/6a5fa3c0e475c39470fceda553e417281c129d2f

You can see it in action here: https://twitter.com/DarkhaxDev/status/1366537794311442432
