### ISSUE TITLE
Suggestion: Centered Tips

### ISSUE THREAD

**Issue by VanillaChan6571** [Darkhax-Minecraft/Tips#29]
I wanted to make centered tips like at the bottom middle I see this is kinda not fit for it but maybe there is a way? If not heres the suggestion.

**Comment by Darkhax** [comment]
Hello, 

It's would be possible to add but it would not look that good. Tips can be any length, and long tips would render on top of, or under buttons and loading text. The current way of doing it works for the most amount of players.
