### ISSUE TITLE
Config toggle to disable default tips

### ISSUE THREAD

**Issue by aaronhowser1** [Darkhax-Minecraft/Tips#32]
instead of having to disable each tip individually in `removedTips = []`

**Comment by aaronhowser1** [comment]
removedNamespaces = ["animal_growing", "arthopods", "baby_panda_slimeball", "barrel", "biome_bonemeal", "biome_fishing", "blaze_snowball", "boat_jump", "boat_passenger", "cooked_drops", "creeper_cat", "creeper_drops_disc", "crouch_blocks", "deflect_ghast_fireballs", "dog_health", "dog_rotten_flesh", "east", "fishing_resources", "fossils", "fortress_triangulation", "four_eggs", "gravity_torch", "iron_golem_heal", "job_site_dimension", "lava_fuel", "lure_animals", "mooshroom_lightning", "nether_lava", "nether_sponge", "note_block_instrument", "piglin_gold", "poison_immune", "scrap_nuggets", "shulker_armor", "shulker_golem", "smoke_bees", "string_wool", "swamp_slimes", "turtle_shell", "undead_damage", "undead_helmet", "villager_sweat", "wandering_invis", "water_grass", "witch_conversion", "wooden_tool_fuel", "zombie_armor"]

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/105659939-85058d80-5e8f-11eb-9716-6d7ff086cdcc.png)
🤦

**Comment by Darkhax** [comment]
It looks like you have misunderstood how the config works. It is a namespace blacklist, not an ID blacklist. The namespace is the part of the ID before the `:` character, for example `tips:swamp_slimes` and `tips:creeper_cat` both have the `tips` namespace. So simply removing the namespace `tips` would remove all the default tips. 

Additionally, if this did accept individual IDs your entries would also be incorrect as none of them have a namespace which is a mandatory part of the ID.
