### ISSUE TITLE
Dynamic Tip Cycle Speed

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Tips#33]
It would be cool if tips cycled at a speed based on the word count of the current tip. Some tips can be read quickly, whilst others are harder to read before it switches to the next tip. Would be nice to see some allowance for that!

**Comment by Darkhax** [comment]
This is a cool idea.

**Comment by Darkhax** [comment]
Tips can now set this by specifying the `cycleTime` in the json. This will default to the CFG specified global time. You can verify the time of an individual tip using the tips list gui (mod list config button).
