### ISSUE TITLE
Disabling default tips, and add custom ones easily

### ISSUE THREAD

**Issue by Nicknaem** [Darkhax-Minecraft/Tips#40]
I found that I can disable all default tips by disabling "tips" namespace via configuration
but how can I add new ones? it also disables tips that I added,
how can I create my own namespace of tips
is there any way to write down tips in only one file easily?

**Comment by Darkhax** [comment]
This is described in the [wiki](https://github.com/Darkhax-Minecraft/Tips/wiki/1.16.3-Documentation#adding-a-tip). The namespace is taken from the folder structure of your resource pack. If the file is `assets/namespace_here/tips/your_tip.json` the ID would be `namespace_here:your_tip`. If the file was `assets/mycoolpack/tips/tip_one.json` the ID would be `mycoolpack:tip_one`.

**Comment by Nicknaem** [comment]
> This is described in the [wiki](https://github.com/Darkhax-Minecraft/Tips/wiki/1.16.3-Documentation#adding-a-tip). The namespace is taken from the folder structure of your resource pack. If the file is `assets/namespace_here/tips/your_tip.json` the ID would be `namespace_here:your_tip`. If the file was `assets/mycoolpack/tips/tip_one.json` the ID would be `mycoolpack:tip_one`.

thank you alot, does mod support adding or disabling tips from game? if not I think this should be the target functionality, adding tips from ingame ui would be very helpful
