### ISSUE TITLE
Issue using Tips with OpenLoader

### ISSUE THREAD

**Issue by DigitalPopsicle** [Darkhax-Minecraft/Tips#48]
I've tried adding my own tips via OpenLoader instead of direct datapacks so I can bundle them with a modpack I'm making, but they don't show up at all. I've even tried the examplepack I found listed in another question but that didn't work either.

I've tried these file formats (popsicle is the namespace)

openloader\data\Popsicle\data\popsicle\tips
openloader\data\Popsicle\assets\popsicle\tips
openloader\assets\Popsicle\tips
openloader\assets\Popsicle\assets\popsicle\tips

I've used tips formated like this:
```
{
    "title": {
      "text": "Adventurer's Tip:",
      "bold": true,
      "color": "green"
    },
    "tip": {
      "text": "Backpacks are a staple for any adventurer. They can be upgraded with various attachments to make them even more useful."
    }
  }
```

And as I've said I've also tried using the examplepack datapack to see if I'd coded things wrong but that doesn't work either.

I don't know what I'm doing wrong or if this mod isn't compatible with OpenLoader

**Comment by Darkhax** [comment]
> I don't know what I'm doing wrong or if this mod isn't compatible with OpenLoader

I make both mods and have tested them together so I can assure you they are compatible.

> openloader\data\Popsicle\data\popsicle\tips
openloader\data\Popsicle\assets\popsicle\tips
openloader\assets\Popsicle\tips
openloader\assets\Popsicle\assets\popsicle\tips

None of these are the correct path. 

```
openloader/resources/yourpack.zip
```
or
```
openloader/resources/your_pack/assets/your_pack_id/tips/your_tip.json
```
