### ISSUE TITLE
how do you remove the default tips

### ISSUE THREAD

**Issue by JetpackRescue** [Darkhax-Minecraft/Tips#52]
the wiki doesn't mention it and the config doesn't have an option to disable the default tips. my tips aren't showing up, in a resource pack i have a tips.json in `assets/your_id/tips`

**Comment by Darkhax** [comment]
The config file has an option to remove specific tips, or entire tip namespaces. Like blocks and items tips have a namespace ID which looks like `namespace:tip_id`. All tips added by this mod (the default tips) are in the `tips` namespace. So adding `tips` to the removed namespaces option will remove all default tips.

When testing your own tips I would recommend using the ingame debug menu. Go to the mod list and click on the Tips mod entry, then click the Config button. This will bring up a GUI with all loaded tips and have additional information about each one. 

![image](https://user-images.githubusercontent.com/2250798/152705336-ad53ca55-e5c4-4380-be51-a6d2e8481117.png)
