### ISSUE TITLE
1.12: Tip text containing single % gives format error

### ISSUE THREAD

**Issue by Gaelmare** [Darkhax-Minecraft/Tips#53]
I have this definition in the config file in 1.12:
```
    S:customTips <
        Powderkegs pack boom into one block with 100% drops...Go find that sulfur
     >

```

This results in a Format Error displayed:
![Screenshot from 2022-02-14 11-03-07](https://user-images.githubusercontent.com/58122689/153920805-77ceaf45-d337-4d45-8497-636e60a986c8.png)

Is there any way to avoid this other than doubling the %? If I do so, other mods displaying tips now need different text than the tips for this mod.

**Comment by Darkhax** [comment]
The tips are formatted using Mojang's text formatter. They reserve % as a special character so a double % is required to escape it.

Under normal circumstances I would look into adding a feature to auto-escape % however this issue is not relevant to modern versions and 1.12 is not supported.
