### ISSUE TITLE
Chinese Localization

### ISSUE THREAD

**Issue by AnzhiZhang** [Darkhax-Minecraft/Tips#56]
I am a contributor to a Chinese Minecraft modpack localization community. I really enjoy your mod because it provides a lot of useful information, and many modpacks I played also use your mod to show their tips. We use resourcepack to localize most mods of Minecraft. This is our main GitHub repo: [Minecraft-Mod-Language-Package](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package).

Recently, we translated your mod Tips' lang file into Chinese, this is the related PR: CFPAOrg/Minecraft-Mod-Language-Package#1916. Most Chinese modpack players are using our resourcepack, so now many Chinese players can see this translation.

For all Chinese players to be able to see the translated tips, would your please pull this Chinese localization into your repo? This is the file link: [zh_cn.json](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/blob/main/projects/1.16/assets/tips/tips/lang/zh_cn.json)

These are all co-authors of this translation, we would appreciate it if you would like to include this in the commit message.
```text
Co-authored-by: Andy Zhang <37402126+AnzhiZhang@users.noreply.github.com>
Co-authored-by: KlparetlR <qq3421037143@163.com>
Co-authored-by: 洛 <3270548757@qq.com>
Co-authored-by: 奈 <58922212@qq.com>
Co-authored-by: n0099 <n@n0099.net>
Co-authored-by: Rinko1231 <89371859+Rinko1231@users.noreply.github.com>
Co-authored-by: mamaruo <37480168+mamaruo@users.noreply.github.com>
Co-authored-by: NostalgiaCyan <cyl18a@gmail.com>
```

Thank you for your assistance.

**Comment by AnzhiZhang** [comment]
Another related Pull Request CFPAOrg/Minecraft-Mod-Language-Package#1962

**Comment by Darkhax** [comment]
Thank you all for working on this. I've added the file and included the co-authors as requested. https://github.com/Darkhax-Minecraft/Tips/commit/21e0794a067eeaf3b1111356cd5de2948dfc177a
