### ISSUE TITLE
[1.18.2] Disabling some default tips makes all tips disappear after joining world. (every tip gets disabled.)

### ISSUE THREAD

**Issue by Gbergz** [Darkhax-Minecraft/Tips#61]
Tips work fine while loading into a world, but after that the tips changes to:
> ("No tips loaded please review your config options!")

![image](https://user-images.githubusercontent.com/26634554/178329144-4f8e2a87-b34c-4c8d-9ee8-6936ca195eff.png)

I've added about 100+ custom ones aswell, nothing loads.

Everything returns to normal if I don't disable any of the default ones. (i.e reset the config back to default.)

Here's the `tips.json` file I use:
https://gist.github.com/Gbergz/ef59ff2d811ef509a3272d446ff8bc7e

**Versions:**
MC: 1.18.2
Forge: 40.1.52
Tips: 5.0.3 | https://www.curseforge.com/minecraft/mc-mods/tips/files/3836415

**Logs**: https://gist.github.com/Gbergz/4b237466aaafab0c14787703fc459457

**-** Gbergz

**Comment by ULSTICK** [comment]
I'm also having the same problem. while its still loaded in the mod settings it seems it still cycles the disabled one but just didn't show it. my tips will still rarely show up.

Video :
https://youtu.be/AoFXSZHCT7Q

My tips.json :
https://pastebin.com/UwpiPuVB

**Comment by aaronhowser1** [comment]
You can overwrite the default tips with empty jsons and it works completely fine!
![image](https://user-images.githubusercontent.com/15698722/185556770-73041470-77b4-4468-94f8-b87fe31e2bf6.png)
Ripped these from the jar and just emptied them, so its just a single empty line.

**Comment by Darkhax** [comment]
@aaronhowser1 I haven't had much time to work on mods lately but I should have a proper fix out as soon as I understand where the code is messing up on this.

**Comment by Darkhax** [comment]
The issue should now be fixed on 1.18.2, updates for 1.19.x will come soon.
