### ISSUE TITLE
[Suggestion] BCLib "Fixing World" Screen Compat

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Tips#62]
Would be cool if tips also displayed on this screen:
![image](https://user-images.githubusercontent.com/24266948/180199691-3522d084-5a45-48cf-8d82-8b1870f8db3b.png)

**Comment by Darkhax** [comment]
Thanks for the suggestion. There is currently no way to extend the list of screens that tips can be displayed on to include non-vanilla screens but I will look into this when I have the time.
