### ISSUE TITLE
Mod-Loading-Error [1.19] [Forge 41.0.110]

### ISSUE THREAD

**Issue by DancerVlt69** [Darkhax-Minecraft/Tips#65]
Minecraft stopped loading with an 'Exception'-Error

![image](https://user-images.githubusercontent.com/49952690/180652219-fefe05ba-bfe1-4f52-bcea-299ddbc8e19b.png)

Crash-Report: [https://pastebin.com/Kkx7KRDi](https://pastebin.com/Kkx7KRDi)

**Comment by ProsperCraft** [comment]
Same, reproduced with only tips mod-
https://gist.githubusercontent.com/ProsperCraft/03a1cece6340c536498b25b655a84a37/raw/47b01de689814a19df4078e6d506c700d351fffe/gistfile1.txt

**Comment by Darkhax** [comment]
There were two different Forge updates that broke a lot of mods. Took a bit but this mod has been updated to work with their updates. Check out 6.1.5 when you're ready to update.

**Comment by DancerVlt69** [comment]
> 

it works fine (also) with the latest Forge 41.1.0 
Thanks for updating @Darkhax
