### ISSUE TITLE
[question] resource pack tips not working

### ISSUE THREAD

**Issue by a-random-something** [Darkhax-Minecraft/Tips#67]
I'm not sure where else to ask this, so I'll just put it here. I can't seem to get custom tips to load. The file structure is resourcepack/assets/tips/tips/tip.json and tip.json looks like this:
 {
  "tip": {
    "text": "Custom tip."
  }
}
It doesn't ever show this tip and instead cycles through the default ones. Any idea of what I'm doing wrong?

**Comment by Darkhax** [comment]
Hello, the issue tracker is generally not the correct place for tech support. You can find an example Resource Pack that works [here](https://darkhax.net/assets/tips/Example-Tip-Pack-1.0.0.zip).
