### ISSUE TITLE
Fabric 1.19 Changing DefaultCycleTime doesn't do anything

### ISSUE THREAD

**Issue by SwShogun** [Darkhax-Minecraft/Tips#69]
I've tried changing it to 10000 for ten seconds, 60000, for a minute, even a huge number to see if it was shmeconds instead of real seconds, etc. but it always cycles every 5 seconds no matter what the value is.

**Comment by Darkhax** [comment]
The issue should now be fixed on 1.18.2, updates for 1.19.x will come soon.
