### ISSUE TITLE
Tips not loading from /kubejs/assets/

### ISSUE THREAD

**Issue by aaronhowser1** [Darkhax-Minecraft/Tips#70]
![image](https://user-images.githubusercontent.com/15698722/185403517-417cbe60-9625-43f7-8fea-3cddd2aa417a.png)
![image](https://user-images.githubusercontent.com/15698722/185403531-246252c3-b530-4b74-8858-daab73e21a2b.png)

The json:
```json
{
    "tip": {
      "text": "MineColonies is integral to the pack's progression."
    }
  }
  ```
  
  config:
  ```json
  {
  "defaultCycleTime": 5000,
  "ignoredNamespaces": [
    "tipsmod"
  ],
  "ignoredTips": []
}
```

Trying the json 
```json
{
  "tip": {
    "translate": "inferno.tip.minecolonies"
  }
}
```
with the lang key 

```json
  "inferno.tip.minecolonies":"MineColonies is essential to the pack's progression."
  ```
added to the en_us.json also does not work.

This is using `Tips-Forge-1.18.2-5.0.4`

**Comment by Darkhax** [comment]
There is currently an issue related to disabling the default tips and this should not be related to kubejs. 

- https://github.com/Darkhax-Minecraft/Tips/issues/61
