### ISSUE TITLE
Tips show in the inventory

### ISSUE THREAD

**Issue by aaronhowser1** [Darkhax-Minecraft/Tips#72]
![image](https://user-images.githubusercontent.com/15698722/186686437-b913048a-f2ff-443f-9f31-55e86ceb89cc.png)

Tips-Forge-1.18.2-5.0.7

**Comment by LaidBackSloth** [comment]
Yes, but only in Creative mode, it looks like

**Comment by aaronhowser1** [comment]
This is weirdly distracting O_o

**Comment by Darkhax** [comment]
Yes it looks like I got confused. I thought tips were already displayed on the survival menu and added it to the creative screen for feature parity. I will revert this change soon.

**Comment by Darkhax** [comment]
This feature has been reverted in

- 5.0.8 for 1.18.2
- 6.1.7 for 1.19
- 7.0.3 for 1.19.1
- 8.0.2 for 1.19.2
