### ISSUE TITLE
German in spanish file

### ISSUE THREAD

**Issue by jarocajavi** [Darkhax-Minecraft/Tips#74]
Hello, i think the old spanish file was be lost, the spanish mexican is ok in its own file, but the spanish (es_es) one is in complete german.

**Comment by Darkhax** [comment]
Thanks for letting me know. I will try to restore this.

**Comment by Darkhax** [comment]
This should be fixed in the next 1.19.2 update. Thanks again for letting me know. https://github.com/Darkhax-Minecraft/Tips/commit/74810967ab8f645898ded38a236f4334fa0d1cb9
