### ISSUE TITLE
[bug] "east" tip incorrect

### ISSUE THREAD

**Issue by fzzyhmstrs** [Darkhax-Minecraft/Tips#75]
the tip: "tipsmod.tip.east": "The Sun, Moon, and Stars all move towards the east.", is not correct. The sun, moon, and stars move towards (set in) the _West_

![image](https://user-images.githubusercontent.com/72876796/192338486-33340014-f30b-409f-ad3c-2b904da3df94.png)

**Comment by audaki** [comment]
+1, wanted to report the same issue 

![image](https://user-images.githubusercontent.com/1321285/192872266-5fb92470-30be-4b10-b9ec-09da2872a590.png)

It's like in real-life, the sun rises in the East, continues South and sets in the West ;-)

**Comment by Darkhax** [comment]
Thanks for the report. I will verify this and make the correction.

**Comment by AngleWyrm10** [comment]
The correction from [east to west](https://github.com/Darkhax-Minecraft/Tips/commit/ce8238f6a04c96f325357af1dfe5c52eed8a73c7) doesn't appear [in the 1.18.2 branch](https://github.com/Darkhax-Minecraft/Tips/blob/1.18.2/Common/src/main/resources/assets/tipsmod/lang/en_us.json), and so I'm not seeing the change when playing Minecraft v1.18.2. 

I've used your extra functionality to disable that tip until/unless 1.18.2 gets a further update.
