### ISSUE TITLE
Configurable time for tips

### ISSUE THREAD

**Issue by IronPiston** [Darkhax-Minecraft/Tips#8]
Currently, tips display for a very short period of time before flashing to the next one. Could a config option be added to set the amount of time tips display before cycling to the next one?

**Comment by Darkhax** [comment]
Thanks for the feature request. There currently is no tip time, it just shows for as long as the transitional GUI is shown. In some circumstances there are multiple loading/transition GUIs consecutively shown which will change the tip shown. There is no way to extend this time without intentionally slowing down world load times. One partial solution would be for the mod to detect consecutive transitional GUIs and prevent the tip from being re-rolled.

**Comment by Darkhax** [comment]
This is now a feature in the 1.16.3 rewrite.
