### ISSUE TITLE
Hacktoberfest and Italian translation 

### ISSUE THREAD

**Issue by ZeroKun265** [Darkhax-Minecraft/Tips#90]
I was wondering if the owner(s) would be willing to opt the repo in the hacktoberfest program.
I want to submit a PR translating the tips in Italian, and I will do so regardless of whether it counts for hacktoberfest or not, but it would be nice if it did :)

**Comment by Darkhax** [comment]
This repo was already part of Hacktoberfest.

**Comment by ZeroKun265** [comment]
#91 Made the PR with italian language
